-- ============================================================
-- Source-Asia Flight Management — Initial Schema Migration
-- ============================================================
-- WHY: We use UUIDs as primary keys for security (non-guessable)
-- and distributed scalability. All timestamps use timestamptz
-- for timezone-aware comparisons.
-- ============================================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- ENUM TYPES
-- ============================================================
-- WHY enums over text: Database-level validation, smaller storage,
-- and prevents invalid state at the lowest level.

CREATE TYPE flight_status AS ENUM ('scheduled', 'boarding', 'departed', 'arrived', 'delayed', 'cancelled');
CREATE TYPE booking_status AS ENUM ('confirmed', 'cancelled', 'rescheduled');
CREATE TYPE seat_status AS ENUM ('available', 'locked', 'booked');
CREATE TYPE seat_class AS ENUM ('economy', 'business', 'first');

-- ============================================================
-- FLIGHTS TABLE
-- ============================================================
-- WHY separate flights table: Normalized design. Flight data is
-- independent of bookings. Supports multiple bookings per flight.

CREATE TABLE flights (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    flight_number TEXT NOT NULL UNIQUE,
    airline TEXT NOT NULL,
    origin TEXT NOT NULL,
    destination TEXT NOT NULL,
    departure_time TIMESTAMPTZ NOT NULL,
    arrival_time TIMESTAMPTZ NOT NULL,
    base_price INTEGER NOT NULL CHECK (base_price > 0),
    status flight_status NOT NULL DEFAULT 'scheduled',
    aircraft_type TEXT NOT NULL DEFAULT 'A320',
    total_seats INTEGER NOT NULL DEFAULT 180,
    available_seats INTEGER NOT NULL DEFAULT 180,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- WHY this constraint: Arrival must be after departure
    CONSTRAINT valid_flight_times CHECK (arrival_time > departure_time),
    -- WHY this constraint: Available seats can't exceed total
    CONSTRAINT valid_seat_count CHECK (available_seats >= 0 AND available_seats <= total_seats)
);

-- ============================================================
-- SEATS TABLE
-- ============================================================
-- WHY per-seat rows: Enables individual seat tracking, real-time
-- updates per seat, and prevents race conditions with row-level locks.

CREATE TABLE seats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    flight_id UUID NOT NULL REFERENCES flights(id) ON DELETE CASCADE,
    seat_number TEXT NOT NULL,
    seat_class seat_class NOT NULL DEFAULT 'economy',
    status seat_status NOT NULL DEFAULT 'available',
    price_modifier INTEGER NOT NULL DEFAULT 0,
    locked_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    locked_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- WHY composite unique: Same seat number can't exist twice on same flight
    CONSTRAINT unique_seat_per_flight UNIQUE (flight_id, seat_number),
    -- WHY this constraint: Locked seats must have lock metadata
    CONSTRAINT valid_lock CHECK (
        (status != 'locked') OR (locked_by IS NOT NULL AND locked_until IS NOT NULL)
    )
);

-- ============================================================
-- BOOKINGS TABLE
-- ============================================================
-- WHY PNR as text: 6-char alphanumeric like real airlines.
-- Generated by RPC function to ensure uniqueness atomically.

CREATE TABLE bookings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    flight_id UUID NOT NULL REFERENCES flights(id) ON DELETE CASCADE,
    pnr TEXT NOT NULL UNIQUE,
    status booking_status NOT NULL DEFAULT 'confirmed',
    total_amount INTEGER NOT NULL CHECK (total_amount > 0),
    passenger_count INTEGER NOT NULL CHECK (passenger_count > 0),
    booked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- PASSENGERS TABLE
-- ============================================================
-- WHY separate from bookings: One booking can have multiple passengers.
-- Passport numbers stored encrypted at rest by Supabase.

CREATE TABLE passengers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    passport_number TEXT,
    seat_number TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- BOOKING_SEATS JUNCTION TABLE
-- ============================================================
-- WHY junction table: Clean many-to-many between bookings and seats.
-- Enables easy seat release on cancellation.

CREATE TABLE booking_seats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    seat_id UUID NOT NULL REFERENCES seats(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- WHY unique constraint: Same seat can only be in one booking
    CONSTRAINT unique_seat_booking UNIQUE (seat_id)
);

-- ============================================================
-- RESCHEDULES TABLE
-- ============================================================
-- WHY audit trail: Tracks all rescheduling history for compliance
-- and customer support resolution.

CREATE TABLE reschedules (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    booking_id UUID NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    old_flight_id UUID NOT NULL REFERENCES flights(id),
    new_flight_id UUID NOT NULL REFERENCES flights(id),
    price_difference INTEGER NOT NULL DEFAULT 0,
    rescheduled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- WHY this constraint: Can't reschedule to same flight
    CONSTRAINT different_flights CHECK (old_flight_id != new_flight_id)
);

-- ============================================================
-- INDEXES
-- ============================================================
-- WHY these indexes: Optimizes the most common query patterns.

-- Flight search indexes
CREATE INDEX idx_flights_origin_dest ON flights(origin, destination);
CREATE INDEX idx_flights_departure ON flights(departure_time);
CREATE INDEX idx_flights_status ON flights(status);
CREATE INDEX idx_flights_search ON flights(origin, destination, departure_time, status);

-- Seat lookup indexes
CREATE INDEX idx_seats_flight ON seats(flight_id);
CREATE INDEX idx_seats_flight_status ON seats(flight_id, status);
CREATE INDEX idx_seats_locked_until ON seats(locked_until) WHERE status = 'locked';

-- Booking lookup indexes
CREATE INDEX idx_bookings_user ON bookings(user_id);
CREATE INDEX idx_bookings_pnr ON bookings(pnr);
CREATE INDEX idx_bookings_flight ON bookings(flight_id);
CREATE INDEX idx_bookings_user_status ON bookings(user_id, status);

-- Passenger lookup
CREATE INDEX idx_passengers_booking ON passengers(booking_id);

-- Booking seats lookup
CREATE INDEX idx_booking_seats_booking ON booking_seats(booking_id);
CREATE INDEX idx_booking_seats_seat ON booking_seats(seat_id);

-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================
-- WHY: Automatically maintains updated_at timestamp without
-- application code needing to set it.

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_flights_updated_at
    BEFORE UPDATE ON flights
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER set_bookings_updated_at
    BEFORE UPDATE ON bookings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- EXPIRED LOCK CLEANUP
-- ============================================================
-- WHY: Seats locked by users who abandoned the flow should
-- become available again. This function is called periodically
-- or before seat queries.

CREATE OR REPLACE FUNCTION release_expired_locks()
RETURNS void AS $$
BEGIN
    UPDATE seats
    SET status = 'available',
        locked_by = NULL,
        locked_until = NULL
    WHERE status = 'locked'
      AND locked_until < NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
